// need to research passing props to render each emoji with props and then have that data passed to the server on click

const emojis = [
  {
    name: 'afraid',
    secondary: '',
    type: 'afraid',
    level: 1,
    emoji: '😓',
  },
  {
    name: 'angry',
    secondary: '',
    type: 'angry',
    level: 1,
    emoji: '😡',
  },
  {
    name: 'annoyed',
    secondary: 'frustrated',
    type: 'angry',
    level: 3,
    emoji: '🙄',
  },
  {
    name: 'anxious',
    secondary: '',
    type: 'fearful',
    level: 2,
    emoji: '😣',
  },
  {
    name: 'bored',
    secondary: '',
    type: 'bad',
    level: 2,
    emoji: '😑',
  },
  {
    name: 'calm',
    secondary: '',
    type: 'happy',
    level: 2,
    emoji: '😌',
  },

  {
    name: 'confused',
    secondary: '',
    type: 'surprised',
    level: 2,
    emoji: '🤔',
  },
  {
    name: 'crazy',
    secondary: 'excited',
    type: 'surprised',
    level: 3,
    emoji: '🤪',
  },
  {
    name: 'disgusted',
    secondary: '',
    type: 'disgusted',
    level: 1,
    emoji: '😒',
  },
  {
    name: 'embarrassed',
    secondary: 'disapproving',
    type: 'disgusted',
    level: 3,
    emoji: '😅',
  },
  {
    name: 'excited',
    secondary: '',
    type: 'surprised',
    level: 2,
    emoji: '😆',
  },
  {
    name: 'happy',
    secondary: '',
    type: 'happy',
    level: 1,
    emoji: '🙂',
  },

  {
    name: 'lonely',
    secondary: '',
    type: 'sad',
    level: 2,
    emoji: '😔',
  },
  {
    name: 'nostalgic',
    secondary: 'peaceful',
    type: 'happy',
    level: 3,
    emoji: '🥲',
  },
  {
    name: 'numb',
    secondary: 'distant',
    type: 'angry',
    level: 3,
    emoji: '😐',
  },
  {
    name: 'optimistic',
    secondary: '',
    type: 'happy',
    level: 2,
    emoji: '😃',
  },
  {
    name: 'proud',
    secondary: '',
    type: 'happy',
    level: 2,
    emoji: '😎',
  },
  {
    name: 'sad',
    secondary: '',
    type: 'sad',
    level: 1,
    emoji: '🙁',
  },

  {
    name: 'sick',
    secondary: 'awful',
    type: 'disgusted',
    level: 3,
    emoji: '🤢',
  },
  {
    name: 'silly',
    secondary: 'playful',
    type: 'happy',
    level: 3,
    emoji: '🤡',
  },
  {
    name: 'sleepy',
    secondary: 'tired',
    type: 'bad',
    level: 3,
    emoji: '😴',
  },
  {
    name: 'stressed',
    secondary: '',
    type: 'bad',
    level: 2,
    emoji: '😤',
  },
  {
    name: 'surprised',
    secondary: '',
    type: 'surprised',
    level: 3,
    emoji: '😮',
  },
  {
    name: 'tired',
    secondary: '',
    type: 'bad',
    level: 2,
    emoji: '🥱',
  },
]; // emojis

export default emojis;
