// need to research passing props to render each emoji with props and then have that data passed to the server on click

const emojis = [
  {
    name: 'Afraid',
    secondary: null,
    type: 'Afraid',
    level: 1,
    emoji: '😓',
  },
  {
    name: 'Angry',
    secondary: null,
    type: 'Angry',
    level: 1,
    emoji: '😡',
  },
  {
    name: 'Annoyed',
    secondary: 'Frustrated',
    type: 'Angry',
    level: 3,
    emoji: '🙄',
  },
  {
    name: 'Anxious',
    secondary: null,
    type: 'Fearful',
    level: 2,
    emoji: '😣',
  },
  {
    name: 'Bored',
    secondary: null,
    type: 'Bad',
    level: 2,
    emoji: '😑',
  },
  {
    name: 'Calm',
    secondary: null,
    type: 'Happy',
    level: 2,
    emoji: '😌',
  },

  {
    name: 'Confused',
    secondary: null,
    type: 'Surprised',
    level: 2,
    emoji: '🤔',
  },
  {
    name: 'Crazy',
    secondary: 'Excited',
    type: 'Surprised',
    level: 3,
    emoji: '🤪',
  },
  {
    name: 'Disgusted',
    secondary: null,
    type: 'Disgusted',
    level: 1,
    emoji: '😒',
  },
  {
    name: 'Embarrassed',
    secondary: 'Disapproving',
    type: 'Disgusted',
    level: 3,
    emoji: '😅',
  },
  {
    name: 'Excited',
    secondary: null,
    type: 'Surprised',
    level: 2,
    emoji: '😆',
  },
  {
    name: 'Happy',
    secondary: null,
    type: 'Happy',
    level: 1,
    emoji: '🙂',
  },

  {
    name: 'Lonely',
    secondary: null,
    type: 'Sad',
    level: 2,
    emoji: '😔',
  },
  {
    name: 'Nostalgic',
    secondary: 'Peaceful',
    type: 'Happy',
    level: 3,
    emoji: '🥲',
  },
  {
    name: 'Numb',
    secondary: 'Distant',
    type: 'Angry',
    level: 3,
    emoji: '😐',
  },
  {
    name: 'Optimistic',
    secondary: null,
    type: 'Happy',
    level: 2,
    emoji: '😃',
  },
  {
    name: 'Proud',
    secondary: null,
    type: 'Happy',
    level: 2,
    emoji: '😎',
  },
  {
    name: 'Sad',
    secondary: null,
    type: 'Sad',
    level: 1,
    emoji: '🙁',
  },

  {
    name: 'Sick',
    secondary: 'Awful',
    type: 'Disgusted',
    level: 3,
    emoji: '🤢',
  },
  {
    name: 'Silly',
    secondary: 'Playful',
    type: 'Happy',
    level: 3,
    emoji: '🤡',
  },
  {
    name: 'Sleepy',
    secondary: 'Tired',
    type: 'Bad',
    level: 3,
    emoji: '😴',
  },
  {
    name: 'Stressed',
    secondary: null,
    type: 'Bad',
    level: 2,
    emoji: '😤',
  },
  {
    name: 'Surprised',
    secondary: null,
    type: 'Surprised',
    level: 3,
    emoji: '😮',
  },
  {
    name: 'Tired',
    secondary: null,
    type: 'Bad',
    level: 2,
    emoji: '🥱',
  },
]; // emojis

export default emojis;
